services:
  - type: web
    name: air-drawing-backend
    runtime: python
    repo: https://github.com/DevKacha/air-drawing-recognition
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
    disk:
      name: model-storage
      mountPath: /opt/render/project/src/model
      sizeGB: 1
